### ISSUE TITLE
Move Test::Warnings to test requires phase

### ISSUE THREAD

**Issue by oalders** [DrHyde/perl-modules-Number-Phone#102]
`Test::Warnings` (along with some other tests) are appearing in the runtime requires phase:

https://metacpan.org/release/DCANTRELL/Number-Phone-3.7003/source/META.json#L55-58

It would be great if they could appear in test requires instead. For example, I see `Test::Warnings` is only being used here:

```
t/deprecations.t:6:5:use Test::Warnings qw(warning);
```

The motivation is that I'm trying to remove test dependencies from a DarkPAN. When test requirements appear as runtime requirements it becomes harder to automate pruning test distributions.

**Comment by DrHyde** [comment]
Thanks. Fixed in 38ef4e230, which will be in the next quarterly release.

**Comment by oalders** [comment]
Thanks @DrHyde!
