### ISSUE TITLE
Doesn't install to user directory.

### ISSUE THREAD

**Issue by vicbitone** [DrHyde/perl-modules-Number-Phone#105]
I'm trying to install module via cpan, it failed.
cpan options configured:
makepl_arg => 'INSTALL_BASE=/home/sr INSTALLMAN1DIR=/home/sr/man/man1 INSTALLMAN3DIR=/home/sr/man/man3',
mbuildpl_arg => '--install_base /home/sr --installman1dir=/home/sr/man/man1 --installman3dir=/home/sr/man/man3',
finally result is this:

Running make install for DCANTRELL/Number-Phone-3.8001.tar.gz
Skip blib/lib/auto/share/dist/Number-Phone/Number-Phone-UK-Data.db (unchanged)
Skip blib/lib/auto/share/dist/Number-Phone/Number-Phone-NANP-Data.db (unchanged)
Manifying 33 pod documents
Manifying 6 pod documents
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
ERROR: Can't create '/usr/local/share/man/man3'
Do not have write permissions on '/usr/local/share/man/man3'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 at -e line 1.
make: *** [Makefile:1172: pure_site_install] Error 13
  DCANTRELL/Number-Phone-3.8001.tar.gz
  /usr/bin/make install UNINST=1 -- NOT OK
----
  You may have to su to root to install the package
  (Or you may want to run something like
    o conf make_install_make_command 'sudo make'
  to raise your permissions.Stopping: 'install' failed for 'Number::Phone'.
Failed during this command:
 DCANTRELL/Number-Phone-3.8001.tar.gz         : install NO

**Comment by DrHyde** [comment]
This doesn't look like a problem with Number::Phone, but one with your CPAN.pm config - possibly you have multiple config files and updated the wrong one.

**Comment by DrHyde** [comment]
Fix now released
