### ISSUE TITLE
Number::Phone::UK fails on read-only filesystems

### ISSUE THREAD

**Issue by sdt** [DrHyde/perl-modules-Number-Phone#107]
We try to run most of our docker containers in read-only mode these days. Trying to validate a UK number we ran into this:

```shell
$ perl -MNumber::Phone -e 'Number::Phone->new("+44 1632 960991")'

DBM::Deep: Cannot sysopen file '/usr/local/lib/perl5/site_perl/5.32.1/auto/share/dist/Number-Phone/Number-Phone-UK-Data.db': Read-only file system
```

It seems `DBM::Deep->new($filename)` opens the file in rw mode, but it will also accept a read-only filehandle.

We're using `--without_uk` as a workaround.

**Comment by DrHyde** [comment]
Ooh, that's an interesting edge-case. And should be easy to fix too.

**Comment by DrHyde** [comment]
Fixed in c7d2bee, please test! This will be in the next quarterly release.

**Comment by sdt** [comment]
I can confirm that fix works for me. Thank you - very much appreciated!

**Comment by DrHyde** [comment]
Thank you for helping me iterate asymptotically towards software perfection :-)

**Comment by DrHyde** [comment]
Released
