### ISSUE TITLE
Unable to parse valid GB freephone

### ISSUE THREAD

**Issue by percivalalb** [DrHyde/perl-modules-Number-Phone#112]
```bash
$ perl -MNumber::Phone -e 'my $p = Number::Phone->new("+44800716598"); print $p // "undef", "\n";'
undef
```
This is a Barclays freephone number and the number is valid on https://libphonenumber.appspot.com/phonenumberparser?number=%2B44800716598 but `Number::Phone` is unable to parse it. I have not looked into the reason why, just there is some discrepancy here. Writing it down here so it is saved.

**Comment by DrHyde** [comment]
Thanks, I'll take a look.

**Comment by DrHyde** [comment]
The most recent release was built using OFCOM data that says numbers in that range are one digit longer than they actually are:
![Screenshot 2022-12-24 at 20 41 09](https://user-images.githubusercontent.com/216826/209450621-e8347cb1-0521-46e9-aec1-ba6e93a11928.png)

**Comment by DrHyde** [comment]
I've put in an egregious hack (0d6430db) for now so it will accept both 9 and 10 digit numbers for that range. That will be in the next release. I'll also contact OFCOM and get them to fix their data up-stream.

**Comment by DrHyde** [comment]
Incidentally, the reason libphonenumber accepts it is that they've applied that evil hack to the whole of the 0800 number range. From `resources/PhoneNumberMetadata.xml`:

```
         <nationalNumberPattern>
           80[08]\d{7}|
           800\d{6}|
           8001111
         </nationalNumberPattern>
```

**Comment by percivalalb** [comment]
Thanks for investigating and the insights into phonenumberlib

**Comment by DrHyde** [comment]
Looks like OFCOM have finally fixed their spreadsheet, so I can get rid of the hack from 0d6430db.
