### ISSUE TITLE
The NANP areacode 600 listed as geographic

### ISSUE THREAD

**Issue by percivalalb** [DrHyde/perl-modules-Number-Phone#113]
> Area code 600 is a telephone area code in the North American Numbering Plan for non-geographic use in Canada

From https://en.wikipedia.org/wiki/Area_code_600

which disagrees with `Number::Phone`

```bash
$ perl -MNumber::Phone -e 'my $p = Number::Phone->new("+1600-555-0000"); print $p->is_geographic, "\n";'
1
```

The other attributes of the 600 arecode may need investigating.

**Comment by DrHyde** [comment]
Thanks, fixed in ec426f05 and will be in the next quarterly release.
