### ISSUE TITLE
The NANP areacode 300 treated as valid

### ISSUE THREAD

**Issue by percivalalb** [DrHyde/perl-modules-Number-Phone#119]
> Area Code 300 has not been assigned for use by the North American Numbering Plan Administrator.

From: https://www.areacodehelp.com/where/area_code_300.shtml

`Number::Phone` seems to be able to parse it (it is a possible future phone number) but then also says it is currently valid:
```
$ perl -MNumber::Phone -e 'my $p = Number::Phone->new("+1300-555-0000"); print $p->is_valid, "\n";'
1
```
The libphonenumber implementation is unable to parse it - which is what I would have expected.
```
$ perl -MNumber::Phone::Lib -e 'my $p = Number::Phone::Lib->new("+1300-555-0000"); print $p // "undef", "\n";'
undef
```

**Comment by DrHyde** [comment]
Number::Phone distinguishes when it can between _valid_ (ie, potentially allocatable) and _allocated_ numbers. Number::Phone::Lib, like libphonenumber, does not. The validity rules for the NANP are here: https://github.com/DrHyde/perl-modules-Number-Phone/blob/5fa2b3e2ef66bb095d5ab7e14041cb04ec874d86/lib/Number/Phone/NANP.pm#L228-L234.

That rule could probably be tightened up a bit - for example, 307 911 1234 is invalid. But I'm not sure of exactly what the rules are for the D/E/F digits. For the 307 area code, I believe that 7 digit local dialling is permitted (maybe even required?) and so 911 is obviously not a valid CO code, but for an area code like 416 which is overlaid with several other area codes I have no idea whether 7 digit dialling is allowed when calling another 416 number (in which case the 911 CO is clearly invalid), or whether 10 digit dialling to other 416 numbers is allowed *as well as* 7 digit dialling, or whether 10 digit dialling is *required* (and if it is whether the 911 CO is now valid as it can't appear at the start of a dialled subscriber number). I haven't been able to find any reliable-looking data source for this.
