### ISSUE TITLE
Formatting bug with +599 telephone numbers

### ISSUE THREAD

**Issue by percivalalb** [DrHyde/perl-modules-Number-Phone#122]
> The country code +599 was assigned to the Netherlands Antilles (dissolved in 2010), and is now in use by Curaçao and the Caribbean Netherlands (Bonaire, Sint Eustatius and Saba)

https://en.wikipedia.org/wiki/Telephone_numbers_in_Cura%C3%A7ao_and_the_Caribbean_Netherlands

The format function no longer seems to work for the +599 country code. Not looked into it more than observing the difference.

- `Number::Phone`  3.8007
```
$  perl -MNumber::Phone -e 'my $p = Number::Phone->new("+5997900000"); print $p->format || "empty", "\n";'
+599 7900000
```

- `Number::Phone`  3.9000
```console
$  perl -MNumber::Phone -e 'my $p = Number::Phone->new("+5997900000"); print $p->format || "empty", "\n";'
empty
```

**Comment by DrHyde** [comment]
Thanks, 9277ad24 should fix that. I'll push out a new release once the CI has finished chewing on it.

**Comment by percivalalb** [comment]
Thanks for looking at it so promptly.

**Comment by DrHyde** [comment]
3.9001 has the fix in and is on its way to the CPAN.
