### ISSUE TITLE
Some numbers aren't recognized as Dutch numbers

### ISSUE THREAD

**Issue by waterkip** [DrHyde/perl-modules-Number-Phone#141]
Hi,

I'm running into an issue with a Dutch number 067xxxxxx which is not recognized as a Dutch number. The module doesn't accept it. According to [Dutch legislation](https://wetten.overheid.nl/BWBR0010198/2023-08-12#Bijlage1) this number is a Videotex and access to data services on other networks

I generated the stub code and I see the following:

```
                'mobile' => '
          (?:
            6[1-58]|
            970\\d
          )\\d{7}
        ',
                'pager' => '66\\d{7}',
                'personal_number' => '',
                'specialrate' => '(90[069]\\d{4,7})|(
```

It would be nice if the following ranges are supported as network_services:
* 067[0-5] (Videotex and access to data services on other networks)
* 06760 (Access to Internet Protocol-based networks and services)
* 067[7-9] (Videotex and access to data services on other networks)

**Comment by waterkip** [comment]
Never mind, I see https://github.com/google/libphonenumber/blob/master/FAQ.md#unsupported / What about M2M (machine to machine) numbers?

From how I read it, these numbers are M2M numbers and therefore unsupported. Closing.

**Comment by DrHyde** [comment]
libphonenumber is mostly concerned with things a user would do with a mobile phone - it's part of Android - which is why it lacks support for some things.

If you want a more fully-featured Number::Phone::NL module that goes beyond what libphonenumber supports (there are already a few of those on the CPAN) then you can do that. If you decide to do that, and you want help with it, please don't hesitate to ask.

**Comment by waterkip** [comment]
Yes I read the FAQ and I also have regular users. So why people are trying to submit M2M numbers is unknown to me. If needed I'll make a Phone::Number::NL module. I don't feel the immediate need to do it. Dutch law is pretty clear about the number plan, so I don't see a reason to add M2M numbers in our system.
