### ISSUE TITLE
`./build-data.sh --force` Suffers from Dependency Issue

### ISSUE THREAD

**Issue by theory** [DrHyde/perl-modules-Number-Phone#27]
./build-data.sh --force
    rebuilding lib/Number/Phone/UK/Data.pm
    rebuilding lib/Number/Phone/NANP/Data.pm
    Can't locate Number/Phone/NANP/Data.pm in @INC (you may need to install the Number::Phone::NANP::Data module) (@INC contains: lib /usr/local/lib/perl5/site_perl/5.20.1/darwin-thread-multi-2level /usr/local/lib/perl5/site_perl/5.20.1 /usr/local/lib/perl5/5.20.1/darwin-thread-multi-2level /usr/local/lib/perl5/5.20.1 .) at lib/Number/Phone/Country.pm line 5.
    BEGIN failed--compilation aborted at lib/Number/Phone/Country.pm line 5.
    Compilation failed in require at build-data.nanp line 13.
    BEGIN failed--compilation aborted at build-data.nanp line 13.
    rebuilding lib/Number/Phone/StubCountry/*.pm
    Can't locate Number/Phone/NANP/Data.pm in @INC (you may need to install the Number::Phone::NANP::Data module) (@INC contains: lib /usr/local/lib/perl5/site_perl/5.20.1/darwin-thread-multi-2level /usr/local/lib/perl5/site_perl/5.20.1 /usr/local/lib/perl5/5.20.1/darwin-thread-multi-2level /usr/local/lib/perl5/5.20.1 .) at build-data.stubs line 12.
    BEGIN failed--compilation aborted at build-data.stubs line 12.

Not sure how Number::Phone::Country can be modified to make the dependency on Number::Phone::NANP::Data optional, at least while building. Is it necessary when building new data? If not, maybe it can just be mocked in `build-data.nanp`.

**Comment by DrHyde** [comment]
Fixed in 28604d

**Comment by theory** [comment]
Did you forget to push it?

**Comment by theory** [comment]
Oh, sorry, there it is. Weird that it's not a link in your comment above.
