### ISSUE TITLE
Please update CPAN module

### ISSUE THREAD

**Issue by aleksandrpanteleymonov** [DrHyde/perl-modules-Number-Phone#36]
Hi!
Can you update CPAN module?
Because a lot of metadata changed since the last build.
Thanks!

**Comment by DrHyde** [comment]
Will do. It'll probably be tomorrow or some time over the weekend.

**Comment by aleksandrpanteleymonov** [comment]
Thanks!

**Comment by DrHyde** [comment]
OFCOM have been arsing about and changed the format of their published data files. I'm gonna have to rewrite the build script for the UK data, so it'll take a bit longer. Sorry.

**Comment by DrHyde** [comment]
Please check that the updated build script produces something that works for you.

**Comment by DrHyde** [comment]
3.0007 uploaded to the CPAN

**Comment by aleksandrpanteleymonov** [comment]
thanks!
