### ISSUE TITLE
Number::Phone::UK::Data is a 65 MB file

### ISSUE THREAD

**Issue by SineSwiper** [DrHyde/perl-modules-Number-Phone#41]
This is one of the biggest modules I've seen on CPAN.  Any module that depends on this one is going to pull in this beast.  This would also increase the memory footprint of any Perl process that uses it.

Why is this file so unnaturally large?  If it has to be this large, it should be split off into its own repo, without a dep link from here to UK::Data.

**Comment by DrHyde** [comment]
Number::Phone::UK::Data is only loaded if you try to parse UK phone numbers, and is designed to keep memory usage down by not loading any more data than is necessary for your queries, at the expense of being a bit slow:

    $ perl -e 'sleep 10' & sleep 5;ps auxww|grep perl|grep sleep
    david    23474  0.1  0.1  4044 1132 pts/3    S    15:53   0:00 perl -e sleep 10
    $ perl -MNumber::Phone -e 'sleep 10' & sleep 5;ps auxww|grep perl|grep sleep
    david    23479  0.8  0.2  4728 2104 pts/3    S    15:53   0:00 perl -MNumber::Phone -e sleep 10
    $ perl -MNumber::Phone -e 'Number::Phone->new("+447979866975");sleep 10' & sleep 5;ps auxww|grep perl|grep sleep;fg
    david    23494  2.4  0.3  6080 3624 pts/3    S    15:55   0:00 perl -MNumber::Phone -e Number::Phone->new("+447979866975");sleep 10

As you can see, loading Number::Phone makes your process less than a MB bigger, and loading Number::Phone::UK::Data makes it only a meg and a half bigger.

If you have evidence that it's eating an unreasonable amount of memory, please open a specific bug report, with instructions for replicating the bug.
