### ISSUE TITLE
Update CPAN Module

### ISSUE THREAD

**Issue by juliogreff** [DrHyde/perl-modules-Number-Phone#50]
Probably one of my colleagues contacted you before about the CPAN module version :)

Brazil recently added a new digit to their cellphone numbers. libphonenumbers is up to date, could you please updated the CPAN module? I have the data in my fork of the repo if that helps you in any way.

Thanks!

**Comment by DrHyde** [comment]
Thanks for letting me know, I'll get that done this week.

Can you give me an example number so I can add a test for it?

**Comment by juliogreff** [comment]
Thanks a lot!

Example numbers:

* Should pass validation: +55 35 9 98 70 56 56
* Shouldn't pass validation anymore: +55 35 98 70 56 56 (the first 9 after the area code is is now required, so old numbers are invalid)

**Comment by DrHyde** [comment]
Hmm according to the libphonenumber regex the first 9 in that number is *optional*, so both validate OK. Note the `9?` [here](https://github.com/googlei18n/libphonenumber/blob/41940f8/resources/PhoneNumberMetadata.xml#L3365).

**Comment by DrHyde** [comment]
I had a look [on the ITU website](http://www.itu.int/dms_pub/itu-t/oth/02/02/T020200001D0001PDFE.pdf) and it's a bit confusing. It indicates that libphonenumber might be Very Wrong - you should probably take this up with them. In the mean time, I'll do a release that will at least accept the new numbers with the extra digit.

**Comment by juliogreff** [comment]
The 9 being optional is acceptable for us for the moment, since it's a human (and usually a Brazilian human) picking up the phone and dialing, but we'll take it up with them indeed. We'll be waiting for the release. Thanks a lot!

**Comment by DrHyde** [comment]
3.0012 is on the CPAN now.
