### ISSUE TITLE
t/10_country-test-br.t fails if Number::Phone::BR is installed

### ISSUE THREAD

**Issue by eserte** [DrHyde/perl-modules-Number-Phone#52]
See http://www.cpantesters.org/cpan/report/a03949e0-7e64-11e5-a7d5-11e9dfbfc7aa for a sample fail report.

**Comment by DrHyde** [comment]
Thanks, fixed in f453093. I'll get an updated release out shortly.

**Comment by DrHyde** [comment]
And released as version 3.0013
