### ISSUE TITLE
 Can't locate Number/Phone/StubCountry/SharedCostServices.pm

### ISSUE THREAD

**Issue by theory** [DrHyde/perl-modules-Number-Phone#57]
Started seeing errors like this in our logs. WTF kind of number is that? Is SharedCostServices a real thing?

It might be useful to change the exception to also log the number that was parsed, to make it easier to try to reproduce the error.

**Comment by theory** [comment]
Here's another one:

    Can't locate Number/Phone/StubCountry/InternationalPremium

**Comment by DrHyde** [comment]
Ah yes, I believe are those weird international services in +8NN and +9NN. At least some of the necessary data appears to be in libphonenumber - eg https://github.com/googlei18n/libphonenumber/blob/master/resources/PhoneNumberMetadata.xml#L24948 - so I should be able to extract them.

**Comment by DrHyde** [comment]
I think you're using an old version of Number::Phone. As of commit 5a7e11f2 you shouldn't ever see this.

**Comment by DrHyde** [comment]
See https://github.com/DrHyde/perl-modules-Number-Phone/issues/8

**Comment by theory** [comment]
Bah, sure enough, we're running 3.0006 in prod. :-(

**Comment by theory** [comment]
Oh, wait, that commit was in 2.12, which was a *long* time ago. We're running into this issue in 3.0006. Will get on 3.0014 shortly and see if it persists.

**Comment by theory** [comment]
Okay, it turns out that the `$SIG{__DIE__}` handler I mentioned in #44 is in fact screwing things up. Checking `$^S` does not do the trick. Grrr.

**Comment by theory** [comment]
Okay, the issue in our code is that the `$SIG{__DIE__}` handler looked like this:

    $SIG{__DIE__} = sub {
        return if $^S;
        log(@_)
    };

But `$^S` is `undef` when doing, say, `eval "use $pkg";`. So I've changed it to

    $SIG{__DIE__} = sub {
        return if $^S // 1;
        log(@_)
    };

And now it shouldn't log an error.
