### ISSUE TITLE
[PATCH] update POD to get whatis entries into generated manpages

### ISSUE THREAD

**Issue by gregoa** [DrHyde/perl-modules-Number-Phone#60]
In Debian we are currently applying the following patch to
Number-Phone.
We thought you might be interested in it too.

    Description: update POD to get whatis entries into generated manpages
    Origin: vendor
    Author: gregor herrmann <gregoa@debian.org>
    Last-Update: 2016-07-02
    

The patch is tracked in our Git repository at
https://anonscm.debian.org/cgit/pkg-perl/packages/libnumber-phone-perl.git/plain/debian/patches/pod-whatis.patch

Thanks for considering,
  gregor herrmann,
  Debian Perl Group

**Comment by DrHyde** [comment]
Thanks, applied, and will be in the next release. Unless someone finds an egregious bug that will be the next quarterly update in December.

**Comment by DrHyde** [comment]
Version 3.3000 is now on the CPAN, including this fix. Thanks!
