### ISSUE TITLE
Can't use undefined value as a HASH reference

### ISSUE THREAD

**Issue by KES777** [DrHyde/perl-modules-Number-Phone#64]
```
$x= Number::Phone->new( '+380619265745' )
Number::Phone::StubCountry::UA=HASH(0x20d0b50)

$x->areaname
ERROR: Can't use an undefined value as a HASH reference at local/lib/perl5/Number/Phone/StubCountry.pm line 55, <STDIN> line 21.
```

**Comment by dracos** [comment]
A data update or similar appears to have fixe this particular number:
```
perl -e'use Number::Phone; $x= Number::Phone->new( "+380619265745" ); print $x->areaname;'
Zaporizhzhia

```
But the general issue remains (e.g. for Australian number). I've made a PR at #82

**Comment by KES777** [comment]
>A data update or similar

What should I update to fix that? Thank you

**Comment by dracos** [comment]
I don't know, I don't know what version you have installed or how you installed it. I recommend that you install the latest version however you installed the version you are using, or ask whoever installed it for you.

**Comment by DrHyde** [comment]
Thanks, I've merged @dracos's PR. This fix will be in the next release to hit the CPAN. When that is released I will notify the mailing list. If you're not on the mailing list please join, it's very low traffic. You can join here: http://lists.scsys.co.uk/cgi-bin/mailman/listinfo/number-phone
