### ISSUE TITLE
NZ mobile numbers have changed format

### ISSUE THREAD

**Issue by singingfish** [DrHyde/perl-modules-Number-Phone#96]
see https://github.com/google/libphonenumber/blob/master/resources/PhoneNumberMetadata.xml#L22048

associated with libphonenumber 8.12.1

I'm seeing problems like this in the wild.

**Comment by singingfish** [comment]
looks like a rebuild `Makefile.PL && make dist` fixes the problem.  Although it'd be nice not to have to rely on my own build.

**Comment by DrHyde** [comment]
That's what my fix will be, hopefully later today :-)

I would like to provide a better way for users to update their own installations, but whatever I do would be unreliable, as it would depend on:

* updated data not requiring any changes to the tests;
* google not changing the data format in libphonenumber

**Comment by DrHyde** [comment]
This should be fixed in 3.6003, which is on its way to the CPAN as we speak.
