### ISSUE TITLE
Validation number for  Côte d’Ivoire (CI)

### ISSUE THREAD

**Issue by kirill-binary** [DrHyde/perl-modules-Number-Phone#99]
Hi there.

We have a problem with validating phone numbers for Côte d’Ivoire (CI). The number format was recently updated https://en.wikipedia.org/wiki/Telephone_numbers_in_Ivory_Coast  (31 January 2021).
I checked that the google phone library is already updated and supports the new format. https://github.com/google/libphonenumber/blob/master/resources/PhoneNumberMetadata.xml#L5776

Could you generate a new version of the module with an updated google phone library?

**Comment by DrHyde** [comment]
release-3.7001 is on its way to the CPAN
